export const ACTIONS = {
  QUESTIONSTYPE: "questionType",
  SHOWMODEL: "showModel",
  CLOSEMODEL: "closeModel",
  ADDCHOICE: "addChoice",
  DELETECHOICE: "deleteChoice",
  UPDATECHOICE: "updateChoice",
  QUESTIONSTEXT: "questionText",
  QUESTIONID: "questionId",
  EDIT_QUESTION: "editQuestion",
  UPDATE_QUESTION: "updateQuestion",
  ADD_QUESTION: "addQuestion",
  DELETE_QUESTION: "deleteQuestion",
  LOADING_TRUE: "loadingTrue",
  LOADING_FALSE: "loadingFalse",
  INITIALLOADING: "initialLoading",
  SHOWLINKMODEL: "showLinkModel",
  LINKBUTTONTEXT: "linkButtonText",
  SHOWDELETESURVEYMODEL: "showDeleteSurveyModel",
};
